#!/usr/bin/env bash

#   gitkeyadd starts ssh-agent and adds keys, or simply re-adds expired keys
# Setup ssh environment
export SSH_AUTH_SOCK=~/.ssh/.ssh-socket
if [ -e ~/.ssh/.ssh-agent-pid ] ; then
        export SSH_AGENT_PID=$(cat ~/.ssh/.ssh-agent-pid)
fi
#   gitkeyadd starts ssh-agent and adds keys, or simply re-adds expired keys
gitkeyadd() {
    ssh-add -l 2>/dev/null >/dev/null
        if [[ $? -eq 2 ]] ; then
            # Exit status 2 means couldn't connect to ssh-agent; start one now
                #   from the man page / http://www.manpagez.com/man/1/ssh-add/
                rm $SSH_AUTH_SOCK
                eval "$(ssh-agent -a $SSH_AUTH_SOCK)"
                # Store PID so we can get it back in other shells
                echo "${SSH_AGENT_PID}" > ~/.ssh/.ssh-agent-pid
                # Prompt user for pass-phrase, but forget keys after 12 hours
                echo Adding keys to new instance of ssh-agent
                ssh-add -t 172800
        elif [[ $# -eq 0 ]] ; then
                # Already running and did't suppress adding keys
                echo Adding keys to existing instance of ssh-agent
                ssh-add -t 172800
        fi
}

#   gitkeydel removes keys and ends the ssh-agent process
gitkeydel() 
{
        ssh-add -l 2>/dev/null >/dev/null
        if [[ $? -ne 2 ]] ; then
            # Delete all loaded identities
            ssh-add -D
            # Attempt to exit ssh-agent
            ssh-agent -k
        else
                echo ssh-agent not currently running
        fi
}
